comment:
  layout: "diff, files"
  behavior: once

coverage:
  precision: 1
  status:
    project:
      default:
        if_ci_failed: success
        # Currently, CI runs on PR branches do not include tests of (a) snapshot
        # handling or (b) legacy reporting; these are only run on schedule
        # triggers. This resuls in an apparent coverage drop of about 90 lines,
        # or 0.46 percent. Allow this.
        threshold: 0.5%
    patch:
      default:
        if_ci_failed: success
