name: MESSAGEix-Transport

on:
  # Uncomment these lines for debugging, but leave them commented on 'main'/'dev'
  # pull_request:
  #   branches: [ main, dev ]
  # push:
  #   branches: [ main, dev ]
  schedule:
  # 01:00 UTC = 02:00 CET = 03:00 CEST
  - cron: "0 1 * * *"
  workflow_dispatch: {}

# Cancel previous runs that have not completed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  report:
    runs-on: self-hosted

    env:
      BASE: "ixmp://ixmp-dev/MESSAGEix-GLOBIOM 1.1-R12/baseline_DEFAULT#21"
      DEST: "ixmp://ixmp-dev/MESSAGEix-GLOBIOM 1.1-T-R12/ci nightly"
      report-key: "transport all"

    strategy:
      matrix:
        SSP:
        - SSP1
        - SSP2
        - SSP3
        - SSP4
        - SSP5

    name: MESSAGEix-Transport ${{ matrix.SSP }}

    steps:
    # Steps for the IIASA self-hosted runner only
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: "17"

    - name: Update Git LFS configuration
      run: |
        git lfs --version

    # Steps from here to ##### are nearly identical to pytest.yaml

    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.MESSAGE_TRADE_PRIVATE_KEY }}
    - name: Check out message_data
      uses: actions/checkout@v3
      with:
        path: message_data
        # lfs: true
        submodules: true

    - name: Fetch Git LFS files
      working-directory: message_data
      run: git lfs checkout

    # Other repositories required for testing

    - uses: actions/setup-python@v4
      with:
        # Latest version testable on GitHub Actions
        # Latest release 3.11 is pending wheels for cx-Oracle
        python-version: "3.10"
        cache: pip
        cache-dependency-path: "**/pyproject.toml"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - uses: iiasa/actions/setup-gams@main
      with:
        version: 35.2.0
        license: ${{ secrets.GAMS_LICENSE }}

    # NB the IIASA-hosted runner does not have permissions to do "sudo apt-get",
    #    so the following doesn't work. Rather, the necessary packages
    #    (graphviz libgraphviz-dev pkg-config) are manually installed on the
    #    host system
    # - uses: ts-graphviz/setup-graphviz@v1

    - name: Install package; upgrade dependencies
      run: pip install --upgrade --upgrade-strategy=eager --editable ./message_data[dl,scgen,tests,transport]

    # By default, the above installs message_data dependencies from PyPI.
    # To run against unreleased code (on `main`, or other branches for
    # open PRs), uncomment or modify the lines below as appropriate.
    - name: Force upgrade to unreleased dependencies
      run: |
        # pip install --upgrade "genno @ git+https://github.com/khaeru/genno.git@main"
        pip install --upgrade "ixmp @ git+https://github.com/iiasa/ixmp.git@main"
        pip install --upgrade "message_ix @ git+https://github.com/iiasa/message_ix.git@main"
        # pip install --upgrade "message-ix-models @ git+https://github.com/iiasa/message-ix-models.git@main"

    # #####

    - name: Configure
      run: |
        from pathlib import Path

        import message_ix_models
        from ixmp import config

        config.add_platform(
            "ixmp-dev",
            "jdbc",
            "oracle",
            "x8oda.iiasa.ac.at:1521/PIXMP2.iiasa.ac.at",
            "ixmp_dev",
            "ixmp_dev",
            jvmargs="-Xmx16G",
        )
        config.set(
            "message local data", Path("${{ github.workspace }}", "report"),
        )
        config.save()

        # Equivalent to "(ixmp|message-ix|mix-models) config show"
        print(config.path.read_text())
      shell: python

    - name: Run MESSAGEix-Transport workflow
      run: mix-models --url="${{ env.BASE }}" transport run "${{ matrix.SSP }} reported"

    - name: Upload results as a build artifact
      uses: actions/upload-artifact@v3
      with:
        name: MESSAGEix-Transport
        path: |
          ${{ github.workspace }}/report/
          !${{ github.workspace }}/report/cache/
        if-no-files-found: error
